name: paged_grid_view
description: GridView with PageScrollPhysics and better scrolling performance by not building items during scrolling.
version: 0.0.1
repository: https://github.com/chris-wolf/paged_grid_view

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: